"""m0 foundations

Revision ID: 72b8f40b5ab6
Revises: 
Create Date: 2026-09-29 21:07:12.212467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from procrastinate.schema import SchemaManager
from sqlalchemy.dialects import postgresql

PARTITIONS_FN = """
CREATE OR REPLACE FUNCTION ensure_analytics_partitions(months_ahead int) RETURNS void AS $$
DECLARE
    start_month date := date_trunc('month', now() AT TIME ZONE 'UTC')::date;
    m date;
BEGIN
    FOR i IN 0..months_ahead LOOP
        m := (start_month + make_interval(months => i))::date;
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF analytics_events FOR VALUES FROM (%L) TO (%L)',
            'analytics_events_' || to_char(m, 'YYYY_MM'),
            m::timestamptz AT TIME ZONE 'UTC',
            (m + interval '1 month')::timestamptz AT TIME ZONE 'UTC'
        );
    END LOOP;
END;
$$ LANGUAGE plpgsql;
"""

def _exec_script(sql: str) -> None:
    """Run a multi-statement script. asyncpg prepares statements, which rejects scripts,
    so go through the raw driver connection (simple query protocol)."""
    op.get_bind().connection.dbapi_connection.run_async(lambda conn: conn.execute(sql))


PROCRASTINATE_DROP = """
DROP TABLE IF EXISTS procrastinate_events, procrastinate_periodic_defers, procrastinate_jobs,
    procrastinate_workers CASCADE;
DO $$
DECLARE r record;
BEGIN
    FOR r IN SELECT p.oid::regprocedure AS sig FROM pg_proc p
             JOIN pg_namespace n ON n.oid = p.pronamespace
             WHERE n.nspname = 'public' AND p.proname LIKE 'procrastinate%' LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS ' || r.sig || ' CASCADE';
    END LOOP;
    FOR r IN SELECT t.typname FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
             WHERE n.nspname = 'public' AND t.typname LIKE 'procrastinate%' AND t.typtype IN ('e', 'c') LOOP
        EXECUTE 'DROP TYPE IF EXISTS ' || quote_ident(r.typname) || ' CASCADE';
    END LOOP;
END $$;
"""

# revision identifiers, used by Alembic.
revision: str = '72b8f40b5ab6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('family_id', sa.UUID(), nullable=True),
    sa.Column('anonymous_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name=op.f('pk_analytics_events')),
    postgresql_partition_by='RANGE (occurred_at)'
    )
    op.create_index(op.f('ix_analytics_events_anonymous_id'), 'analytics_events', ['anonymous_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_name'), 'analytics_events', ['name'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('llm_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('family_id', sa.UUID(), nullable=True),
    sa.Column('feature', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_micros', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cost_source', sa.String(length=16), nullable=False),
    sa.Column('price_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    op.create_index(op.f('ix_llm_usage_family_id'), 'llm_usage', ['family_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_occurred_at'), 'llm_usage', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_llm_usage_user_id'), 'llm_usage', ['user_id'], unique=False)
    op.create_table('model_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('input_per_million', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('output_per_million', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cached_input_per_million', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_prices'))
    )
    op.create_index(op.f('ix_model_prices_model'), 'model_prices', ['model'], unique=False)
    op.create_table('outbox_messages',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_outbox_messages')),
    sa.UniqueConstraint('id', name=op.f('uq_outbox_messages_id'))
    )
    op.create_table('user_activity_daily',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'activity_date', 'platform', name=op.f('pk_user_activity_daily'))
    )
    # ### end Alembic commands ###
    op.create_index(
        "ix_outbox_messages_pending", "outbox_messages", ["seq"], postgresql_where=sa.text("dispatched_at IS NULL")
    )

    # Monthly partitions for analytics_events; the worker calls this daily to stay 3 months ahead.
    op.execute(PARTITIONS_FN)
    op.execute("CREATE TABLE analytics_events_default PARTITION OF analytics_events DEFAULT")
    op.execute("SELECT ensure_analytics_partitions(3)")

    # Procrastinate job queue schema (its own tables, functions and types).
    _exec_script(SchemaManager.get_schema())


def downgrade() -> None:
    """Downgrade schema."""
    _exec_script(PROCRASTINATE_DROP)
    op.execute("DROP FUNCTION IF EXISTS ensure_analytics_partitions(int)")
    op.drop_index("ix_outbox_messages_pending", table_name="outbox_messages")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_activity_daily')
    op.drop_table('outbox_messages')
    op.drop_index(op.f('ix_model_prices_model'), table_name='model_prices')
    op.drop_table('model_prices')
    op.drop_index(op.f('ix_llm_usage_user_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_occurred_at'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_family_id'), table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_name'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_anonymous_id'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
