"""m4 planning

Revision ID: 7cedd886d852
Revises: 22590bc6f362
Create Date: 2026-09-29 22:19:04.488279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cedd886d852'
down_revision: Union[str, Sequence[str], None] = '22590bc6f362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('participants_hint', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_via', sa.String(length=16), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(all_day AND start_date IS NOT NULL AND starts_at IS NULL) OR (NOT all_day AND starts_at IS NOT NULL AND start_date IS NULL)', name=op.f('ck_events_timed_or_all_day')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_events_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_events_family_id_families'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_family_id'), 'events', ['family_id'], unique=False)
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.create_index(op.f('ix_events_starts_at'), 'events', ['starts_at'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignee_hint', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_via', sa.String(length=16), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name=op.f('fk_tasks_completed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tasks_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_tasks_family_id_families'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_family_id'), 'tasks', ['family_id'], unique=False)
    op.create_index('ix_tasks_family_open', 'tasks', ['family_id'], unique=False, postgresql_where=sa.text("status = 'open'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_family_open', table_name='tasks', postgresql_where=sa.text("status = 'open'"))
    op.drop_index(op.f('ix_tasks_family_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_events_starts_at'), table_name='events')
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_index(op.f('ix_events_family_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
