"""m4 draft actions

Revision ID: dc2f6a57da10
Revises: 7cedd886d852
Create Date: 2026-09-29 22:22:25.754733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc2f6a57da10'
down_revision: Union[str, Sequence[str], None] = '7cedd886d852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('command', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('revision_of', sa.UUID(), nullable=True),
    sa.Column('result_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_draft_actions_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_draft_actions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_actions'))
    )
    op.create_index(op.f('ix_draft_actions_family_id'), 'draft_actions', ['family_id'], unique=False)
    op.create_index('ix_draft_actions_pending', 'draft_actions', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_draft_actions_pending', table_name='draft_actions', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_draft_actions_family_id'), table_name='draft_actions')
    op.drop_table('draft_actions')
    # ### end Alembic commands ###
